name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - python-dotenv
  - pytest
  - beautifulsoup4
  - requests
  - regex
  - openai
  - json
  - pip
  - pip:
      - pyautogen
      - autogen